### ISSUE TITLE
building error: incompatible type for argument 1 of ‘__builtin_ia32_pblendvb128’

### ISSUE THREAD

**Issue by YizhuoZhai** [GJDuck/EffectiveSan#7]
Hi:

I'm trying to build EffectiveSan from source code (using ./build.sh), but encounter those errors, could you please help?

```sh 
.../EffectiveSan/EffectiveSan/llvm-4.0.1.src/projects/compiler-rt/lib/effective/effective.c:44:36: error: incompatible type for argument 1 of ‘__builtin_ia32_pblendvb128’
         __builtin_ia32_pblendvb128(bounds1, bounds2, cmp);
                                    ^
.../EffectiveSan/llvm-4.0.1.src/projects/compiler-rt/lib/effective/effective.c:44:36: note: expected ‘__vector(16) char’ but argument is of type ‘EFFECTIVE_BOUNDS {aka __vector(2) long int}’
/data2/yizhuo/EffectiveSan/EffectiveSan/llvm-4.0.1.src/projects/compiler-rt/lib/effective/effective.c:44:45: error: incompatible type for argument 2 of ‘__builtin_ia32_pblendvb128’
         __builtin_ia32_pblendvb128(bounds1, bounds2, cmp);
                                             ^
.../EffectiveSan/llvm-4.0.1.src/projects/compiler-rt/lib/effective/effective.c:44:45: note: expected ‘__vector(16) char’ but argument is of type ‘EFFECTIVE_BOUNDS {aka __vector(2) long int}’
/data2/yizhuo/EffectiveSan/EffectiveSan/llvm-4.0.1.src/projects/compiler-rt/lib/effective/effective.c:44:54: error: incompatible type for argument 3 of ‘__builtin_ia32_pblendvb128’
         __builtin_ia32_pblendvb128(bounds1, bounds2, cmp);
                                                      ^
.../EffectiveSan/llvm-4.0.1.src/projects/compiler-rt/lib/effective/effective.c:239:43: error: incompatible type for argument 1 of ‘__builtin_ia32_pmovmskb128’
     int mask = __builtin_ia32_pmovmskb128(cmp);
                                           ^
```

**Comment by GJDuck** [comment]
Are you building on a very old machine that does not support SSE 4.1?

**Comment by YizhuoZhai** [comment]
> 

I use a machine with Intel(R) Xeon(R) CPU E5-2695, which seems does not support SSE 4.1. Any idea if I do not have such advanced CPU?

**Comment by GJDuck** [comment]
The E5-2695 isn't that old (from 2016), so I would be surprised if SSE 4.1 is not supported.  SSE 4.1 was first introduced in ~2008 I think.

Check `/proc/cpuinfo` for `sse4_1` and `popcnt`.  If missing, then maybe it disabled somehow, e.g., some versions of bios can disable CPU features.

**Comment by YizhuoZhai** [comment]
> The E5-2695 isn't that old (from 2016), so I would be surprised if SSE 4.1 is not supported. SSE 4.1 was first introduced in ~2008 I think.
> 
> Check `/proc/cpuinfo` for `sse4_1` and `popcnt`. If missing, then maybe it disabled somehow, e.g., some versions of bios can disable CPU features.

I checked the /proc/cpuinfo and it shows both sse4_1 and popcnt in flags, I assume this means they are not disabled. But I still get the error, why?

**Comment by GJDuck** [comment]
This one has me stumped.  Perhaps try updating the build script(s) to explicitly pass `-msse4.1` to the compiler(s).

**Comment by YizhuoZhai** [comment]
> This one has me stumped. Perhaps try updating the build script(s) to explicitly pass `-msse4.1` to the compiler(s).

I add the -msse4.1 to the ./build.sh but with no luck, is this the only place that I should add the option?

**Comment by GJDuck** [comment]
I do not know how to fix this issue.

**Comment by YizhuoZhai** [comment]
I can try more, will get back if I fix the issue.

**Comment by YizhuoZhai** [comment]
> I do not know how to fix this issue.

I got more detailed error message showing as:
EffectiveSan/llvm-4.0.1.src/projects/compiler-rt/lib/effective/effective.c:44:36: error: incompatible type for argument 1 of ‘
__builtin_ia32_pblendvb128’
   44 |         __builtin_ia32_pblendvb128(bounds1, bounds2, cmp);
      |                                    ^~~~~~~
      |                                    |
      |                                    EFFECTIVE_BOUNDS {aka __vector(2) long int}
Any idea to solve it?

**Comment by YizhuoZhai** [comment]
Hi Gregory:
I think that would be related to the gcc version to compile the LLVM, so, do you still remember the gcc version you use in your experiment?

**Comment by GJDuck** [comment]
That would be the gcc version from ubuntu 16.04, which is gcc version 5.4.0.

**Comment by YizhuoZhai** [comment]
Hi Gregory:
This compiling error is solved by the explicit casting, I did the following:
typedef char EFFECTIVE_BOUNDS2 EFFECTIVE_VECTOR_SIZE(16);
 __builtin_ia32_pblendvb128((EFFECTIVE_BOUNDS2)bounds1, (EFFECTIVE_BOUNDS2)bounds2, (EFFECTIVE_BOUNDS2)cmp);

**Comment by GJDuck** [comment]
Thanks for solving it, perhaps create a PR?

**Comment by YizhuoZhai** [comment]
> Thanks for solving it, perhaps create a PR?

Done, please check.

**Comment by wliuxingxiangyu** [comment]
> Hi Gregory: This compiling error is solved by the explicit casting, I did the following: typedef char EFFECTIVE_BOUNDS2 EFFECTIVE_VECTOR_SIZE(16); __builtin_ia32_pblendvb128((EFFECTIVE_BOUNDS2)bounds1, (EFFECTIVE_BOUNDS2)bounds2, (EFFECTIVE_BOUNDS2)cmp);

@YizhuoZhai 
Hi, Thanks for your patch, 
https://github.com/GJDuck/EffectiveSan/pull/10/commits/d8145cb0b21e7dc5a4719cd98eb9686ab1350991

typedef char EFFECTIVE_BOUNDS2 EFFECTIVE_VECTOR_SIZE(16);
__builtin_ia32_pblendvb128((EFFECTIVE_BOUNDS2)bounds1, (EFFECTIVE_BOUNDS2)bounds2, (EFFECTIVE_BOUNDS2)cmp);

But when I use your patch, I found the message:

`EffectiveSan/llvm-4.0.1.src/projects/compiler-rt/lib/effective/effective.c:44:2: error: incompatible types when initializing type ‘EFFECTIVE_BOUNDS {aka __vector(2) long int}’ using type ‘__vector(16) char’`

I wonder if I miss some code?  Thank you again!
