### ISSUE TITLE
The Overhead Split for the FireFox

### ISSUE THREAD

**Issue by YizhuoZhai** [GJDuck/EffectiveSan#8]
Hi:
I read the overhead from the paper as "The results for standard browser benchmarks are shown in Figure 10. Overall we see that EffectiveSan (full) intro- duces a 422% overhead compared to the uninstrumented baseline, which is (1.5×) the additional overhead compared to the SPEC2006 results. ".

Have you ever split the overhead between the type check and bound check? As the Figure. 8 shown.

**Comment by GJDuck** [comment]
EffectiveSan is intended to be run in (full) mode with both type+bounds checking.  So we never did such an experiment with FireFox.

We did test some reduced-instrumentation versions of EffectiveSan in Figure 8.  This was mainly to show that the bounds checking overhead from the implementation was not unreasonable, as explained in the paper: *The main motivation for the
variants is to enable a meaningful comparison with related tools*.

Figure 8 is also not a breakdown, the (full) version offers more protection than both the (bounds) and (type) versions combined.

**Comment by YizhuoZhai** [comment]
Thanks!
