### ISSUE TITLE
How did you evaluate the Firefox?

### ISSUE THREAD

**Issue by YizhuoZhai** [GJDuck/EffectiveSan#9]
Hi Gregory:
I wonder how did you evaluate the overhead on the Firefox, did you use pure terminal command or the GUI? Is there a ny standard benchmark to do so?

**Comment by GJDuck** [comment]
It was using the GUI, with some standard browser benchmarks (please check the paper for the specific benchmarks used).

**Comment by YizhuoZhai** [comment]
> It was using the GUI, with some standard browser benchmarks (please check the paper for the specific benchmarks used).

I checked the paper and get a graph, but have no idea how to repeat your test, could you please give me a hint? I'm new new to the Firefox development and have no idea to get my hands on it.

**Comment by GJDuck** [comment]
Check the name of the benchmark & Google for it.  Some of the benchmarks may now be defunct, however.
